### PR TITLE
Added support for actions

### LINKED ISSUE #244: Add support for actions
Actions are essentially pub/sub + clients/services, both of which are already implemented, so this should be relatively straightforward.

### PR DESCRIPTION
**Pull request by esteve**
WIP

Closes #244

### CODE REVIEW

**Comment by maspe36** [comment]
Hey @esteve, I'm interested in helping out with this. Is there anything in particular you'd like help with?

**Comment by esteve** [comment]
@maspe36 thanks for the offer, but for now I rather continue working on this, hopefully I'll have an action server soon. If you'd like to contribute to `ros2_rust` , perhaps you might be interested in https://github.com/ros2-rust/ros2_rust/issues/130, it doesn't seem that @nnmm has started to work on it.

**Comment by nnmm** [comment]
I have started, though not much progress the last couple of months.

**Comment by maspe36** [comment]
I'll take a look, thanks :+1:

**Comment by pmirabel** [comment]
> Do anyone have any updates on this? I am keen to get ROS2 action working on Rust since it has much potential for various applications.
> 
> Anything I can help with?

Hello :) @esteve , would it be possible to get some feedback on this ? 
Maybe I could help if needed ?

**Comment by esteve** [comment]
Superseded by #410

**Pull request closed without merging**
