### PR TITLE
ci: refactor workflow

### PR DESCRIPTION
**Pull request by wep21**
Use actions below.
https://github.com/ros-tooling/action-ros-ci
https://github.com/actions-rs/toolchain

### CODE REVIEW

**Comment by wep21** [comment]
@esteve Could you review this?

**Comment by wep21** [comment]
@esteve @jhdcs friendly ping

**Review by jhdcs — APPROVED** [review]
I apologize! I didn't get a notification for some reason!

The changes look simple enough to me, so this should be fine! I'm going to approve these changes, unless @esteve can see something that I missed...

**Comment by esteve** [comment]
@wep21 sorry, I didn't see the notification, thanks for the ping :slightly_smiling_face: LGTM, thanks!

**Comment by esteve** [comment]
@jhdcs thanks for reviewing this PR

**Pull request merged**
