### PR TITLE
Version 0.4.0

### PR DESCRIPTION
**Pull request by esteve**

### CODE REVIEW

**Comment by esteve** [comment]
This is the text I'll use for the release:

Highlights for this release:

 - Preliminary support for parameters (https://github.com/ros2-rust/ros2_rust/pull/332)
 - Support for Iron Irwini (https://github.com/ros2-rust/ros2_rust/pull/319)
 - Serde big array support (https://github.com/ros2-rust/ros2_rust/pull/328)
 - Basic functionality for loading introspection type support libraries (https://github.com/ros2-rust/ros2_rust/pull/279)
 - Extend string types (https://github.com/ros2-rust/ros2_rust/pull/293)
 - Add time source and clock API to nodes (https://github.com/ros2-rust/ros2_rust/pull/325)
 - Removed Galactic support (https://github.com/ros2-rust/ros2_rust/pull/306)
 - Removed Foxy support (https://github.com/ros2-rust/ros2_rust/pull/318)

Thanks to all the contributors that made this release possible:

Fawdlstty @fawdlstty
Uwe Arzt @uwearzt 
Luca Della Vedova @luca-della-vedova 
Michael Grey @mxgrey 
Sam Privett @maspe36 
Carter Schultz @Carter12s 

@jhdcs @nnmm @maspe36 @Carter12s @mxgrey @luca-della-vedova can you check that everyting is ok? Thanks.

**Comment by esteve** [comment]
@jhdcs I think it's caused by a change in the traits in `rosidl_runtime_rs`. I've bumped the depepdency version for it and hopefully Cargo won't use the version that's in crates.io

**Comment by maspe36** [comment]
Do we not want to highlight the addition of the time source API? Other than that LGTM, will approve once the builds passing

**Comment by esteve** [comment]
> Do we not want to highlight the addition of the time source API? Other than that LGTM, will approve once the builds passing

It's there:

Add time source and clock API to nodes (https://github.com/ros2-rust/ros2_rust/pull/325)

Or do you mean something else?

**Comment by maspe36** [comment]
Oh, whoops, my mistake. Apologies, it's quite early on the west coast 😁

**Comment by esteve** [comment]
@jhdcs it's fixed now

**Review by jhdcs — APPROVED** [review]

**Comment by jhdcs** [comment]
Looks good to me!

Once again, thank you **very** much to everyone who contributed! This would not have been possible without you!

**Pull request merged**
