### PR TITLE
Move rclrs_examples to examples/minimal_pub_sub

### PR DESCRIPTION
**Pull request by nnmm**
We want to add new packages for further examples, which can then go into the `examples` directory. I also renamed the package to better follow the naming schema of `rclcpp` and `rclpy` examples.

### CODE REVIEW

**Review by jhdcs — APPROVED** [review]

**Comment by nnmm** [comment]
Thanks for the quick review! I'm giving @esteve a day or so to leave comments since I think he might have some.

**Comment by nnmm** [comment]
Forgot to adapt the README too, done now.

**Comment by nnmm** [comment]
@jhdcs Could you re-review? I realized that I should create a new package for the message demo, since it's not related to pub-sub.

**Review by esteve — APPROVED** [review]

**Comment by esteve** [comment]
@jhdcs @nnmm what do you think of moving the examples to a separate repo? Like https://github.com/ros2/examples does

**Review by jhdcs — APPROVED** [review]

**Comment by jhdcs** [comment]
I think that might be a good idea! It would keep the crate size down, and follow how ROS does things.

**Comment by esteve** [comment]
I've created https://github.com/ros2-rust/examples, we can move the examples there later once this PR is merged.

**Comment by nnmm** [comment]
I'm fine with a separate repo.

**Pull request merged**
