### PR TITLE
Add comments explaining each dependency

### PR DESCRIPTION
**Pull request by nnmm**
I got the idea from this reddit post: https://www.reddit.com/r/rust/comments/u5cjmu/dependency_justification_section_may_need_more/

### CODE REVIEW

**Review by jhdcs — CHANGES_REQUESTED** [review]
Looks good, but should there be comments for the examples crate as well? To fully document everything going on for ROS 2 users not used to Rust (and vice-versa)? Or would this be repeating ourselves too much?

**Comment by nnmm** [comment]
> Looks good, but should there be comments for the examples crate as well? To fully document everything going on for ROS 2 users not used to Rust (and vice-versa)? Or would this be repeating ourselves too much?

I looked at the `rclrs_examples/Cargo.toml` but decided not to comment it for now. It's just anyhow + message packages, so there's nothing interesting to say about these, and I also think this convention applies more to libraries than binaries. If you'd like me to, I can add it though.

**Review by jhdcs — APPROVED** [review]
If you feel that adding the extra comments will be too confusing/verbose, then I will defer to your judgement. Otherwise, everything looked good to me!

**Comment by nnmm** [comment]
Thanks!

**Pull request merged**
