### PR TITLE
Add service_is_ready()

### PR DESCRIPTION
**Pull request by Carter12s**
I was digging around for some low hanging fruit issues to get my feet wet with the crate and found https://github.com/ros2-rust/ros2_rust/pull/218 that was stuck in limbo.

Since I saw that #249 had merged with support for guard conditions I thought I might take a crack at revising that MR. After digging in for a bit I came to the conclusion that #249 didn't include all needed tooling and that to match the rclcpp implementation we'd need support for graph events (I think?).

That was more than I was ready to bite off, but I decided part of the #218 was still of value, so submitted a trimmed down version of that here.

### CODE REVIEW

**Comment by esteve** [comment]
@Carter12s so good to see you here! :slightly_smiling_face: Overall, the changes look good, can you fix the `clippy` issues? Thanks.

**Comment by Carter12s** [comment]
@esteve Happy to be here! Updated

**Review by jhdcs — APPROVED** [review]
This seems a simple and clean enough change to me. Thank you very much for your contribution!

**Review by esteve — APPROVED** [review]

**Comment by esteve** [comment]
@Carter12s thanks!

**Pull request merged**
