### PR TITLE
Improve efficiency of deserializing strings

### PR DESCRIPTION
**Pull request by nnmm**
This addresses part of https://github.com/ros2-rust/ros2_rust/issues/214.

I recommend watching the excellent https://www.youtube.com/watch?v=BI_bHCGRgMY tutorial. I mostly followed the implementation of the standard library `String` type.

### CODE REVIEW

**Comment by esteve** [comment]
@nnmm cool! Looks like there's an issue with the generated Python files for `rclrs_example_msgs`, but it's not cause by this PR, might be a problem in `rolling`.

**Comment by nnmm** [comment]
@esteve yeah. Unfortunately the workaround suggested in https://github.com/ros-tooling/action-ros-ci/issues/795 didn't seem to actually work around, so we'd have to wait for the next Rolling sync. Can we somehow make CI allow failure (for this specific check or entirely) until then?

**Comment by esteve** [comment]
@nnmm looks like that's a feature that users have requested (https://github.com/orgs/community/discussions/15452), I don't know of any other way to allow a job to fail. I think the best we can do now is disable the `rolling` CI job until the next sync.

**Comment by esteve** [comment]
@nnmm never mind, looks like `continue-on-error` might work in this case: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error

**Comment by esteve** [comment]
I've created https://github.com/ros2-rust/ros2_rust/pull/302 to allow the `rolling` job to fail, let's see if it works.

**Comment by nnmm** [comment]
@esteve Could you take another look now that CI is green?

**Review by esteve — APPROVED** [review]
@nnmm thanks!

**Pull request merged**
