### PR TITLE
Basic functionality for loading introspection type support libraries

### PR DESCRIPTION
**Pull request by nnmm**
Given a topic type in the form of a string like "geometry_msgs/msg/Pose", this will
* Parse the string into the package name "geometry_msgs" and the message name "Pose" (see the `MessageTypeName` type)
* Search the ament index for the prefix of the "geometry_msgs" package. In the prefix, the introspection type support library will be in `lib/libgeometry_msgs__rosidl_typesupport_introspection_c.so` (via the `ament_rs` crate)
* Load that library using `libloading` (see `get_type_support_library()`)
* Extract the symbol corresponding to the "Pose" type from that library (see `get_type_support_handle()`)

This commit intentionally leaves out an important part of the `DynamicMessageMetadata` type: The representation of the message structure. This will follow in another commit.

### CODE REVIEW

**Comment by esteve** [comment]
@nnmm have you looked into https://github.com/PlotJuggler/plotjuggler-ros-plugins/tree/development/plugins/ros2_introspection? This may solve a similar problem and/or serve as inspiration.

**Comment by nnmm** [comment]
@esteve Thanks for the link, I didn't know that one yet. I think [my branch](https://github.com/ros2-rust/ros2_rust/pull/262) already covers the functionality from that package and more.

**Review by jhdcs — DISMISSED** [review]
Sorry for the wait, this seems good to me! I don't see any glaring issues, at any rate.

**Comment by nnmm** [comment]
Thank you very much @jhdcs!

@esteve, do you have any further comments? Otherwise I'll go ahead and merge this.

**Comment by nnmm** [comment]
@jhdcs Could you reapprove? I had to rebase onto main.

**Review by jhdcs — APPROVED** [review]

**Comment by nnmm** [comment]
Thank you!

**Pull request merged**
