### PR TITLE
Update CI and README.md to use the main branch

### PR DESCRIPTION
**Pull request by esteve**

### CODE REVIEW

**Comment by esteve** [comment]
CI is not running for this PR because I've updated the config, it should be triggered once the `master` branch gets renamed

**Review by nnmm — COMMENTED** [review]
Could you also update the link at the top of lib.rs?

**Comment by esteve** [comment]
> Could you also update the link at the top of lib.rs?

Good catch! Updated. Thanks.

**Review by nnmm — APPROVED** [review]
LGTM!

**Comment by esteve** [comment]
@nnmm thanks for the prompt review :slightly_smiling_face:

**Pull request merged**
