### PR TITLE
Added rustdoc check step to CI

### LINKED ISSUE #113: Add rustdoc check step to CI
We can check with `cargo rustdoc -- -D warnings` whether a package's documentation contains any warnings or errors. This could be another step in the CI pipeline.

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
Closes #113

### CODE REVIEW

**Comment by nnmm** [comment]
I think this won't work yet – you need to execute this in each package's directory, not the top-level directory.

**Comment by mohitsaxenaknoldus** [comment]
> I think this won't work yet – you need to execute this in each package's directory, not the top-level directory.

Oh! My bad...check now?

**Comment by nnmm** [comment]
Could you do it the same way as the clippy step? That should work.

**Comment by mohitsaxenaknoldus** [comment]
> Could you do it the same way as the clippy step? That should work.

Done.

**Comment by nnmm** [comment]
You removed the filter for `ament_cargo` packages, so now it tries to run rustdoc on Python and CMake packages too.

**Comment by mohitsaxenaknoldus** [comment]
> You removed the filter for `ament_cargo` packages, so now it tries to run rustdoc on Python and CMake packages too.

Oh! I thought we wanted this for every package, my bad! Fixed.

**Comment by nnmm** [comment]
Now we're getting somewhere – though now it can't find the dependencies, because the `.cargo` folder is in a different folder.

If you add back the `cd ${{ steps.build.outputs.ros-workspace-directory-name }}` from the clippy step, it should probably work.

**Comment by mohitsaxenaknoldus** [comment]
> Now we're getting somewhere – though now it can't find the dependencies, because the `.cargo` folder is somewhere else.
> 
> If you add back the `cd ${{ steps.build.outputs.ros-workspace-directory-name }}` from the clippy step, it should probably work. That's where the `colcon build` command ran, so it contains the `.cargo` folder.

Added

**Comment by nnmm** [comment]
Looks like we also need the last command from clippy, sourcing the ROS 2 installation. I wasn't sure about that.

**Comment by mohitsaxenaknoldus** [comment]
> Looks like we also need the last command from clippy, sourcing the ROS 2 installation. I wasn't sure about that.

This one?
`. /opt/ros/${{ matrix.ros_distro }}/setup.sh`

**Comment by nnmm** [comment]
Yep

**Comment by nnmm** [comment]
Looks like `rclrs_examples` is failing the rustdoc step, because it contains multiple binaries.

I'd suggest to just filter out `rclrs_examples` for now.

**Comment by mohitsaxenaknoldus** [comment]
> Looks like `rclrs_examples` is failing the rustdoc step, because it contains multiple binaries.
> 
> I'd suggest to just filter out `rclrs_examples` for now.

Done.

**Comment by nnmm** [comment]
I can't see where you filtered it out?

**Comment by mohitsaxenaknoldus** [comment]
> I can't see where you filtered it out?

`for path in $(colcon list | awk '$3 == "(ament_cargo)" { print $2 }' | sed -n 'p;n'); do`

**Comment by mohitsaxenaknoldus** [comment]
> Ah, thanks. That works, but it's not obvious what it's intended to do. Could you do this instead? `awk '$3 == "(ament_cargo)" && $1 != "rclrs_examples" { print $2 }'`

Done

**Review by nnmm — APPROVED** [review]

**Comment by nnmm** [comment]
Thanks!

**Pull request merged**
