### PR TITLE
Add Nikolai and Jacob to authors in Cargo.toml and maintainers in package.xml

### PR DESCRIPTION
**Pull request by nnmm**
I'm happy to add other people like (@jhdcs) too, I just didn't want to speak for them on the question of whether they want to be listed there.

As far as I understand, the semantics of the `authors` field in Cargo.toml is different from the one in `package.xml` in that it doesn't necessarily only list the original author(s).

### CODE REVIEW

**Comment by jhdcs** [comment]
I will abstain from a review in this instance, as I feel like it's @esteve 's call.

**Comment by nnmm** [comment]
@jhdcs: Could you confirm that you want to be listed in these files?

**Comment by jhdcs** [comment]
Eventually, though I will have to see how my work prefers my email to appear - I am no longer at DCS, and am not sure how public my new email should be.

**Comment by nnmm** [comment]
> Can you add yourself and @jhdcs as maintainers in the package.xml file as well? Thanks.

Done.

**Review by esteve — DISMISSED** [review]

**Comment by nnmm** [comment]
@jhdcs Should I also update your old email address to the new one in the packages that already have you as an author?

**Comment by nnmm** [comment]
> @jhdcs Should I also update your old email address to the new one in the packages that already have you as an author?

Done.

**Comment by nnmm** [comment]
Could you re-approve?

**Review by esteve — APPROVED** [review]

**Pull request merged**
