### PR TITLE
Remove references to rclrs not being on crates.io

### PR DESCRIPTION
**Pull request by esteve**
Fixes https://github.com/ros2-rust/ros2_rust/issues/334

### CODE REVIEW

**Review by maspe36 — APPROVED** [review]
So it should be possible to build an rclrs node without having the entirety of ros2_rust in your workspace or an underlay?

**Comment by esteve** [comment]
@maspe36 I'm afraid I'm a bit lost here, is your comment about https://github.com/ros2-rust/ros2_rust/pull/380 ?

**Comment by maspe36** [comment]
I am specifically referring to this removed line
> *Note: Once `rclrs` is published on crates.io, it's not technically needed anymore to clone the `ros2_rust` repo, and this section will be modified to reflect that.*

It sounds like once I run these commands,

```
cargo install --debug cargo-ament-build 
pip install git+https://github.com/colcon/colcon-cargo.git
pip install git+https://github.com/colcon/colcon-ros-cargo.git
```

I could write a node in rust that pulls rclrs from crates.io when I `colcon build`. Is that understanding correct?

**Comment by mxgrey** [comment]
I'd love to be wrong about this but I think for now you'd at least need to have `rosild_generator_rs` in your colcon workspace with the message packages that you need. If we can get that package on the build farm then I think the usage you're describing would work.

**Pull request merged**
