### PR TITLE
Bump setup-ros action in CI to support Ubuntu Jammy

### PR DESCRIPTION
**Pull request by flynneva**
Signed-off-by: Evan Flynn <evan.flynn@apex.ai>

### CODE REVIEW

**Comment by flynneva** [comment]
@esteve this should fix the CI error - just had to bump the `setup-ros` action I think

**Comment by flynneva** [comment]
@esteve spoke to soon.  gimme a bit.

**Comment by flynneva** [comment]
@esteve welp I guess [the jammy docker container is not available yet](https://hub.docker.com/r/rostooling/setup-ros-docker/tags?page=1) so my bad on that. I thought it was. I'll just comment it out for now since in a few weeks it will be available.

The rolling update to `jammy` though is still applicable.

**Comment by esteve** [comment]
> welp I guess the jammy docker container is not available yet so my bad on that.

No problem! Sorry, I should have waited for the CI to finish before merging the other PR. How would you like to proceed here? Shall we roll back the changes in other PR or attempt to fix the issues in this one?

**Comment by flynneva** [comment]
> How would you like to proceed here?

@esteve sorry I was off at lunch. I'll fix this now (it is almost there!)

**Comment by flynneva** [comment]
@esteve the change that is left here is really this one: that `rolling` CI now [uses Ubuntu Jammy 22.04](https://github.com/ros2-rust/ros2_rust/runs/6459992286?check_suite_focus=true#step:2:15).

Once the setup-ros humble container is available we can uncomment those lines as well.

**Review by esteve — APPROVED** [review]

**Comment by esteve** [comment]
@flynneva thanks!

**Pull request merged**
