### PR TITLE
Add SAFETY comments to all unsafe blocks in rclrs

### PR DESCRIPTION
**Pull request by nnmm**

### CODE REVIEW

**Review by jhdcs — CHANGES_REQUESTED** [review]
Looks pretty good to me! I only noticed one spot that was missed! Unfortunately GitHub won't let me link it, because it's not close enough to a changed line (I think that's the reason, anyway), but it's in `mod.rs`, line 37, in the Drop implementation for NodeHandle.

**Comment by nnmm** [comment]
@jhdcs Right, I left that out because that part is changed in https://github.com/ros2-rust/ros2_rust/pull/102/files, but it makes sense to add it here already and then transfer that comment over. Done.

**Review by esteve — DISMISSED** [review]
@nnmm awesome work! Thanks

**Review by esteve — DISMISSED** [review]

**Comment by nnmm** [comment]
@jhdcs Could you approve this PR?

**Review by jhdcs — DISMISSED** [review]

**Comment by nnmm** [comment]
Sorry, I'd need another approval because I just merged #102 and rebased.

**Review by esteve — APPROVED** [review]

**Comment by nnmm** [comment]
Thanks!

**Pull request merged**
