### PR TITLE
Use nightly for style check

### PR DESCRIPTION
**Pull request by mxgrey**
Related to https://github.com/ros2-rust/ros2_rust/issues/395

### CODE REVIEW

**Review by maspe36 — APPROVED** [review]
Can you add a comment in the rustfmt file mentioning that it requires nightly? 

Or perhaps we should have a tracking issue like [this](https://github.com/LibertyDSNP/frequency/issues/1895)?

**Review by esteve — DISMISSED** [review]
@mxgrey thanks! I agree with @maspe36 , a comment about style checking requiring nightly would be nice

**Review by esteve — APPROVED** [review]
@mxgrey LGTM, thanks!

**Comment by mxgrey** [comment]
Comment added in 0aaf01d

I think opening an issue is fine, but realistically I'm not expecting this situation to change in the foreseeable future. It seems that a surprising number of rustfmt settings have been stuck on nightly for many years.

**Review by maspe36 — APPROVED** [review]

**Pull request merged**
