### PR TITLE
Generalize callbacks for subscriptions

### PR DESCRIPTION
**Pull request by nnmm**
By implementing a trait (`SubscriptionCallback`) on valid function signatures, and making subscriptions accept callbacks that implement this trait, we can now

* Receive both plain and boxed messages
* Optionally receive a MessageInfo along with the message, as the second argument
* Soon, receive a loaned message instead of an owned one

This corresponds to the functionality in `any_subscription_callback.hpp` in `rclcpp`.

Closes https://github.com/ros2-rust/ros2_rust/issues/257

### CODE REVIEW

**Comment by esteve** [comment]
@nnmm is this ready for review? I saw some new commits since you requested a review. If it's not ready, could you mark it as a draft? Thanks.

**Comment by nnmm** [comment]
@esteve It is ready. Generally I only assign people when it is ready for review (even though in some cases like this, I still need to fix some small CI hiccups).

**Review by jhdcs — APPROVED** [review]
I really like this PR! It makes things look a lot cleaner! Hopefully that translates to easier use/maintainability as well!

**Review by esteve — APPROVED** [review]
@nnmm this is so great and clean. I did it for rclcpp (https://github.com/ros2/rclcpp/blob/rolling/rclcpp/include/rclcpp/function_traits.hpp) and it was a really ugly.

I'll port this to services handle functions to optionally take a rmw_request_id_t

**Comment by nnmm** [comment]
Aw thanks, you guys will make me blush. Good idea to port it to service handle functions!

About the extension to loaned messages myself, you previously proposed to create a ticket for it so that maybe you could help with it, but since it's a really straightforward extension of this PR that will only take a couple of minutes I'd do it myself if you don't mind. But I'll leave the port to service handle functions to you.

**Pull request merged**
